"""News aggregation pipeline for the AUA AI Hub.

Behavior follows SPEC.md section 8: fetch -> normalize -> filter -> dedupe ->
curate -> write. Phase 2 implements keyword curation mode; LLM mode arrives in
Phase 3 and falls back to this code path.

Generated outputs (never hand-edit): docs/news/*.md, docs/news/archive/*,
includes/latest.md, docs/digest.xml, data/seen_items.json.

data/seen_items.json is the single pipeline state file: a rolling 60-day
ledger of canonical URLs and title hashes (dedupe), plus metadata for kept
items (so news pages can show the latest 15 across runs) and the digest
history (so digest.xml can retain the 12 most recent weekly digests).

Usage:
    python scripts/aggregate.py --dry-run --verbose   # always dry-run first
    python scripts/aggregate.py
Flags: --dry-run (no writes), --no-llm (force keyword mode), --since-days N
(override lookback window), --verbose (per-feed and per-drop detail).
"""

import argparse
import hashlib
import html
import json
import re
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from email.utils import format_datetime
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit
from xml.sax.saxutils import escape

import feedparser
import requests
import yaml
from dateutil import parser as dateparser
from rapidfuzz import fuzz

REPO = Path(__file__).resolve().parent.parent
FEEDS_PATH = REPO / "feeds.yaml"
LEDGER_PATH = REPO / "data" / "seen_items.json"
NEWS_DIR = REPO / "docs" / "news"
ARCHIVE_DIR = NEWS_DIR / "archive"
LATEST_INCLUDE = REPO / "includes" / "latest.md"
DIGEST_PATH = REPO / "docs" / "digest.xml"

USER_AGENT = "AUA-AI-Hub pipeline (github.com/TarronKayAUA/aua-ai-hub)"
RETRIES = 2  # additional attempts after the first
KEEP_PER_CATEGORY = 8  # keyword-mode keep budget per category per run
PAGE_ITEMS = 15  # items shown on each category page (SPEC section 8)
LATEST_ITEMS = 5  # items in the homepage include
DIGEST_KEEP = 12  # digests retained in the RSS channel
LEDGER_DAYS = 60  # rolling ledger window
FUZZY_THRESHOLD = 92  # rapidfuzz ratio for title duplicates
TITLE_FUZZY_FLOOR = 20  # skip fuzzy compare for very short titles

TRACKING_PARAMS = {"fbclid", "gclid", "dclid", "mc_cid", "mc_eid", "igshid", "spm"}

GENERATED_HEADER = (
    "<!-- GENERATED by scripts/aggregate.py. Do not hand-edit; changes will "
    "be overwritten by the next pipeline run. -->"
)

PAGE_INTROS = {
    "general_ai": "Model releases, benchmarks, and developments in general "
    "artificial intelligence.",
    "medical_education": "Research and news on artificial intelligence in "
    "medical education.",
    "clinical_practice": "Artificial intelligence in clinical care, "
    "deployment, and regulation.",
}

SELECTION_NOTE = (
    "Items are selected nightly by an automated pipeline and link to their "
    "original sources. See [About](../about.md) for how selection works."
)


@dataclass
class Item:
    title: str
    url: str
    source: str
    published: datetime
    summary: str
    category: str
    weight: float = 1.0
    score: float = 0.0
    first_seen: str = ""

    def to_ledger(self, kept: bool, now_iso: str) -> dict:
        record = {
            "url": self.url,
            "title_hash": title_hash(self.title),
            "first_seen": now_iso,
            "kept": kept,
        }
        if kept:
            record.update(
                title=self.title,
                source=self.source,
                published=self.published.isoformat(),
                summary=self.summary,
                category=self.category,
                score=round(self.score, 2),
            )
        return record


# --- text utilities ---------------------------------------------------------


def strip_html(text: str) -> str:
    text = re.sub(r"<[^>]+>", " ", text)
    text = html.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def remove_dashes(text: str) -> str:
    """Site style rule: no em dashes in rendered copy (CLAUDE.md)."""
    text = re.sub(r"(?<=\w)[–—](?=\w)", "-", text)  # ranges: 2024-2025
    text = re.sub(r"\s*[–—]+\s*", ", ", text)
    return text


def clean_text(text: str, limit: int = 500) -> str:
    text = remove_dashes(strip_html(text))
    if len(text) > limit:
        text = text[: limit - 1].rsplit(" ", 1)[0] + "…"
    return text


def title_hash(title: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "", title.lower())
    return hashlib.sha256(normalized.encode()).hexdigest()[:32]


def canonicalize(url: str) -> str:
    parts = urlsplit(url.strip())
    query = [
        (k, v)
        for k, v in parse_qsl(parts.query, keep_blank_values=True)
        if not k.lower().startswith("utm_") and k.lower() not in TRACKING_PARAMS
    ]
    path = parts.path.rstrip("/") or "/"
    return urlunsplit(
        (parts.scheme.lower(), parts.netloc.lower(), path, urlencode(query), "")
    )


def md_escape(text: str) -> str:
    return text.replace("[", r"\[").replace("]", r"\]")


def fmt_date(dt: datetime) -> str:
    return dt.strftime("%B %d, %Y").replace(" 0", " ")


# --- fetch and normalize ----------------------------------------------------


def fetch_feed(url: str, timeout: int, verbose: bool) -> bytes:
    last_error = None
    for attempt in range(1 + RETRIES):
        try:
            resp = requests.get(
                url, headers={"User-Agent": USER_AGENT}, timeout=timeout
            )
            if resp.status_code >= 400:
                raise requests.HTTPError(f"HTTP {resp.status_code}")
            return resp.content
        except requests.RequestException as exc:
            last_error = exc
            if verbose:
                print(f"    attempt {attempt + 1} failed: {exc}")
            if attempt < RETRIES:
                time.sleep(2)
    raise RuntimeError(str(last_error))


def parse_entry_date(entry) -> datetime | None:
    for key in ("published_parsed", "updated_parsed"):
        struct = entry.get(key)
        if struct:
            return datetime(*struct[:6], tzinfo=timezone.utc)
    for key in ("published", "updated", "date"):
        raw = entry.get(key)
        if raw:
            try:
                parsed = dateparser.parse(raw)
            except (ValueError, OverflowError):
                continue
            if parsed:
                if parsed.tzinfo is None:
                    parsed = parsed.replace(tzinfo=timezone.utc)
                return parsed.astimezone(timezone.utc)
    return None


def normalize(parsed, source: str, category: str, weight: float, max_items: int,
              counters: dict) -> list[Item]:
    items = []
    for entry in parsed.entries:
        link = entry.get("link")
        title = clean_text(entry.get("title", ""), limit=300)
        if not link or not title:
            counters["no_link_or_title"] += 1
            continue
        published = parse_entry_date(entry)
        if published is None:
            counters["no_date"] += 1
            continue
        summary_raw = entry.get("summary") or entry.get("description") or ""
        if not summary_raw and entry.get("content"):
            summary_raw = entry["content"][0].get("value", "")
        items.append(
            Item(
                title=title,
                url=canonicalize(link),
                source=source,
                published=published,
                summary=clean_text(summary_raw),
                category=category,
                weight=weight,
            )
        )
    items.sort(key=lambda i: i.published, reverse=True)
    return items[:max_items]


# --- ledger -----------------------------------------------------------------


def load_ledger() -> dict:
    if LEDGER_PATH.exists():
        ledger = json.loads(LEDGER_PATH.read_text(encoding="utf-8"))
    else:
        ledger = {}
    ledger.setdefault("items", [])
    ledger.setdefault("digests", [])
    ledger.setdefault("last_digest_week", "")
    return ledger


def prune_ledger(ledger: dict, now: datetime) -> int:
    cutoff = (now - timedelta(days=LEDGER_DAYS)).isoformat()
    before = len(ledger["items"])
    ledger["items"] = [i for i in ledger["items"] if i["first_seen"] >= cutoff]
    return before - len(ledger["items"])


# --- rendering --------------------------------------------------------------


def render_item_md(record: dict) -> str:
    published = datetime.fromisoformat(record["published"])
    line = (
        f"- **[{md_escape(record['title'])}]({record['url']})**  \n"
        f"  *{record['source']}, {fmt_date(published)}.*"
    )
    if record.get("summary"):
        line += f" {record['summary']}"
    return line


def kept_records(ledger: dict, category: str | None = None) -> list[dict]:
    records = [
        r for r in ledger["items"]
        if r.get("kept") and (category is None or r.get("category") == category)
    ]
    records.sort(key=lambda r: r["published"], reverse=True)
    return records


def render_category_page(label: str, intro: str, records: list[dict]) -> str:
    lines = [GENERATED_HEADER, "", f"# {label}", "", intro, "", SELECTION_NOTE, ""]
    if records:
        lines.extend(render_item_md(r) for r in records)
    else:
        lines.append("No items yet. The pipeline adds items nightly.")
    return "\n".join(lines) + "\n"


def render_latest_include(records: list[dict]) -> str:
    lines = [GENERATED_HEADER, ""]
    for record in records:
        published = datetime.fromisoformat(record["published"])
        lines.append(
            f"- [{md_escape(record['title'])}]({record['url']}) "
            f"({record['source']}, {fmt_date(published)})"
        )
    if not records:
        lines.append("No items yet. The pipeline adds items nightly.")
    return "\n".join(lines) + "\n"


def digest_description_html(categories: dict, by_category: dict) -> str:
    parts = []
    for key, records in by_category.items():
        if not records:
            continue
        parts.append(f"<h3>{escape(categories[key])}</h3><ul>")
        for r in records:
            summary = escape(r.get("summary", ""))
            parts.append(
                f'<li><a href="{escape(r["url"])}">{escape(r["title"])}</a> '
                f"({escape(r['source'])}). {summary}</li>"
            )
        parts.append("</ul>")
    return "".join(parts)


def digest_markdown(categories: dict, by_category: dict, week_label: str) -> str:
    lines = [
        GENERATED_HEADER,
        "",
        f"# This Week",
        "",
        f"Digest for {week_label}. " + SELECTION_NOTE,
        "",
    ]
    empty = True
    for key, records in by_category.items():
        if not records:
            continue
        empty = False
        lines.extend([f"## {categories[key]}", ""])
        lines.extend(render_item_md(r) for r in records)
        lines.append("")
    if empty:
        lines.append("No items were kept this week.")
    return "\n".join(lines) + "\n"


def render_digest_xml(site_url: str, digests: list[dict]) -> str:
    items_xml = []
    for d in digests:
        items_xml.append(
            "    <item>\n"
            f"      <title>{escape(d['title'])}</title>\n"
            f"      <link>{escape(d['link'])}</link>\n"
            f"      <guid isPermaLink=\"false\">{escape(d['guid'])}</guid>\n"
            f"      <pubDate>{escape(d['pub_date'])}</pubDate>\n"
            f"      <description>{escape(d['description'])}</description>\n"
            "    </item>"
        )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<rss version="2.0">\n'
        "  <channel>\n"
        "    <title>AUA AI Hub Weekly Digest</title>\n"
        f"    <link>{escape(site_url)}</link>\n"
        "    <description>Weekly digest of artificial intelligence news for "
        "the AUA College of Medicine community.</description>\n"
        + "\n".join(items_xml)
        + "\n  </channel>\n</rss>\n"
    )


def render_archive_index(archive_files: list[str]) -> str:
    lines = [
        GENERATED_HEADER,
        "",
        "# News Archive",
        "",
        "Weekly digests, newest first.",
        "",
    ]
    for name in archive_files:
        stem = name.removesuffix(".md")
        year, week = stem.split("-w")
        lines.append(f"- [Week {int(week)}, {year}]({name})")
    if not archive_files:
        lines.append("No archived weeks yet.")
    return "\n".join(lines) + "\n"


# --- main pipeline ----------------------------------------------------------


def read_site_url() -> str:
    # Light-touch read; mkdocs.yml is plain YAML in this project.
    config = yaml.safe_load((REPO / "mkdocs.yml").read_text(encoding="utf-8"))
    return config["site_url"]


def main() -> int:
    argp = argparse.ArgumentParser(description=__doc__)
    argp.add_argument("--dry-run", action="store_true", help="no writes")
    argp.add_argument("--no-llm", action="store_true", help="force keyword mode")
    argp.add_argument("--since-days", type=int, default=None,
                      help="override lookback window")
    argp.add_argument("--verbose", action="store_true")
    args = argp.parse_args()

    now = datetime.now(timezone.utc)
    now_iso = now.isoformat()

    config = yaml.safe_load(FEEDS_PATH.read_text(encoding="utf-8"))
    defaults = config["defaults"]
    lookback_days = args.since_days or defaults["lookback_days"]
    timeout = defaults["request_timeout_seconds"]
    max_items = defaults["max_items_per_feed"]
    block_terms = [t.lower() for t in config["keyword_block"]]
    boost_terms = [t.lower() for t in config["keyword_boost"]]
    categories = {k: v["label"] for k, v in config["categories"].items()}

    # 1. fetch + 2. normalize
    feeds_attempted = 0
    feeds_skipped = []
    feeds_failed = []
    feeds_succeeded = []
    norm_counters = {"no_date": 0, "no_link_or_title": 0}
    raw_count = 0
    all_items: list[Item] = []

    for cat_key, cat in config["categories"].items():
        for feed in cat.get("feeds", []):
            name, url = feed["name"], feed["url"]
            if url == "TODO-OWNER":
                feeds_skipped.append(name)
                continue
            feeds_attempted += 1
            if args.verbose:
                print(f"fetching {name} ({url})")
            try:
                content = fetch_feed(url, timeout, args.verbose)
            except RuntimeError as exc:
                feeds_failed.append(f"{name}: {exc}")
                continue
            parsed = feedparser.parse(content)
            if not parsed.entries:
                feeds_failed.append(f"{name}: parsed but 0 entries")
                continue
            raw_count += len(parsed.entries)
            items = normalize(
                parsed, name, cat_key, float(feed.get("weight", 1.0)),
                max_items, norm_counters,
            )
            feeds_succeeded.append(name)
            all_items.extend(items)

    if feeds_attempted and not feeds_succeeded:
        print("FATAL: every feed failed", file=sys.stderr)
        for failure in feeds_failed:
            print(f"  {failure}", file=sys.stderr)
        return 2

    # 3. lookback window + block filter
    cutoff = now - timedelta(days=lookback_days)
    in_window = [i for i in all_items if i.published >= cutoff]
    after_window = len(in_window)

    def blocked(item: Item) -> bool:
        text = f"{item.title} {item.summary}".lower()
        return any(term in text for term in block_terms)

    unblocked = []
    for item in in_window:
        if blocked(item):
            if args.verbose:
                print(f"  blocked: {item.title[:60]}")
        else:
            unblocked.append(item)
    after_block = len(unblocked)

    # 4. dedupe: exact URL, fuzzy title, then seen ledger
    unblocked.sort(key=lambda i: i.published, reverse=True)
    by_url: dict[str, Item] = {}
    for item in unblocked:
        by_url.setdefault(item.url, item)
    deduped_urls = list(by_url.values())

    fuzzy_kept: list[Item] = []
    for item in deduped_urls:
        duplicate = False
        for kept in fuzzy_kept:
            if (
                len(item.title) >= TITLE_FUZZY_FLOOR
                and fuzz.ratio(item.title.lower(), kept.title.lower())
                >= FUZZY_THRESHOLD
            ):
                duplicate = True
                if args.verbose:
                    print(f"  fuzzy dup: {item.title[:60]}")
                break
        if not duplicate:
            fuzzy_kept.append(item)

    ledger = load_ledger()
    pruned = prune_ledger(ledger, now)
    seen_urls = {r["url"] for r in ledger["items"]}
    seen_hashes = {r["title_hash"] for r in ledger["items"]}
    fresh = [
        i for i in fuzzy_kept
        if i.url not in seen_urls and title_hash(i.title) not in seen_hashes
    ]
    after_dedupe = len(fresh)

    # 5. curate (keyword mode in Phase 2; --no-llm reserved for Phase 3)
    mode = "keyword"
    kept_by_category: dict[str, list[Item]] = {k: [] for k in categories}
    for item in fresh:
        text = f"{item.title} {item.summary}".lower()
        matches = sum(1 for term in boost_terms if term in text)
        item.score = matches + item.weight
    for cat_key in categories:
        pool = [i for i in fresh if i.category == cat_key]
        pool.sort(key=lambda i: (-i.score, -i.published.timestamp()))
        kept_by_category[cat_key] = pool[:KEEP_PER_CATEGORY]
    kept_items = [i for pool in kept_by_category.values() for i in pool]
    kept_set = {id(i) for i in kept_items}

    # ledger update: everything fresh is now seen; kept items carry metadata
    for item in fresh:
        ledger["items"].append(item.to_ledger(id(item) in kept_set, now_iso))

    # 6. outputs
    files_written: list[tuple[str, int]] = []

    def write(path: Path, content: str, count: int):
        rel = path.relative_to(REPO).as_posix()
        if args.dry_run:
            print(f"[dry-run] would write {rel} ({count} items)")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
            files_written.append((rel, count))

    slug = {"general_ai": "general-ai", "medical_education": "medical-education",
            "clinical_practice": "clinical-practice"}
    for cat_key, label in categories.items():
        records = kept_records(ledger, cat_key)[:PAGE_ITEMS]
        page = render_category_page(label, PAGE_INTROS[cat_key], records)
        write(NEWS_DIR / f"{slug[cat_key]}.md", page, len(records))

    latest = kept_records(ledger)[:LATEST_ITEMS]
    write(LATEST_INCLUDE, render_latest_include(latest), len(latest))

    # weekly digest when the ISO week has changed since the last digest
    iso = now.isocalendar()
    week_key = f"{iso.year}-W{iso.week:02d}"
    digest_written = False
    if week_key != ledger["last_digest_week"]:
        monday = now.date() - timedelta(days=now.weekday())
        week_label = f"the week of {monday.strftime('%B %d, %Y').replace(' 0', ' ')}"
        window_start = (now - timedelta(days=7)).isoformat()
        by_category = {
            k: [r for r in kept_records(ledger, k) if r["first_seen"] >= window_start]
            for k in categories
        }
        digest_count = sum(len(v) for v in by_category.values())
        digest_entry = {
            "guid": f"aua-ai-digest-{iso.year}-W{iso.week:02d}",
            "title": f"AUA AI Hub Digest: Week of "
            f"{monday.strftime('%B %d, %Y').replace(' 0', ' ')}",
            "link": read_site_url() + "news/this-week/",
            "pub_date": format_datetime(now),
            "description": digest_description_html(categories, by_category),
        }
        digest_md = digest_markdown(categories, by_category, week_label)
        write(NEWS_DIR / "this-week.md", digest_md, digest_count)
        write(ARCHIVE_DIR / f"{iso.year}-w{iso.week:02d}.md", digest_md, digest_count)
        if not args.dry_run:
            ledger["digests"].append(digest_entry)
            ledger["digests"] = ledger["digests"][-DIGEST_KEEP:]
            ledger["last_digest_week"] = week_key
        digests_newest_first = list(reversed(ledger["digests"] + (
            [digest_entry] if args.dry_run else [])))
        # On dry runs the entry was not appended; the line above previews it.
        digests_newest_first = list({d["guid"]: d for d in digests_newest_first}.values())
        write(DIGEST_PATH, render_digest_xml(read_site_url(), digests_newest_first),
              len(digests_newest_first))
        archive_files = sorted(
            (p.name for p in ARCHIVE_DIR.glob("*-w*.md")), reverse=True
        ) if ARCHIVE_DIR.exists() else []
        if args.dry_run and f"{iso.year}-w{iso.week:02d}.md" not in archive_files:
            archive_files = sorted(
                archive_files + [f"{iso.year}-w{iso.week:02d}.md"], reverse=True
            )
        write(ARCHIVE_DIR / "index.md", render_archive_index(archive_files),
              len(archive_files))
        digest_written = True

    if not args.dry_run:
        write_count = len(ledger["items"])
        LEDGER_PATH.parent.mkdir(parents=True, exist_ok=True)
        LEDGER_PATH.write_text(
            json.dumps(ledger, indent=1, ensure_ascii=False),
            encoding="utf-8", newline="\n",
        )
        files_written.append(("data/seen_items.json", write_count))

    # 7. verification block
    kept_total = len(kept_items)
    per_cat_counts = {categories[k]: len(v) for k, v in kept_by_category.items()}
    print("\n=== verification ===")
    print(f"curation mode    : {mode}")
    print(f"feeds attempted  : {feeds_attempted}")
    print(f"feeds succeeded  : {len(feeds_succeeded)}")
    print(f"feeds failed     : {len(feeds_failed)}")
    for failure in feeds_failed:
        print(f"  FAIL {failure}")
    print(f"feeds skipped    : {len(feeds_skipped)} (TODO-OWNER)")
    print(f"raw items        : {raw_count}")
    print(f"normalize drops  : no_date={norm_counters['no_date']} "
          f"no_link_or_title={norm_counters['no_link_or_title']}")
    print(f"after window     : {after_window} (lookback {lookback_days} days)")
    print(f"after block      : {after_block}")
    print(f"after dedupe     : {after_dedupe} "
          f"(url dups {after_block - len(deduped_urls)}, "
          f"fuzzy dups {len(deduped_urls) - len(fuzzy_kept)}, "
          f"already seen {len(fuzzy_kept) - after_dedupe})")
    print(f"kept total       : {kept_total}")
    for label, count in per_cat_counts.items():
        print(f"  {label:<18}: {count}")
    print(f"ledger pruned    : {pruned} entries older than {LEDGER_DAYS} days")
    print(f"weekly digest    : {'written (' + week_key + ')' if digest_written else 'not due'}")
    if args.dry_run:
        print("files written    : none (dry run)")
    else:
        print(f"files written    : {len(files_written)}")
        for rel, count in files_written:
            print(f"  {rel} ({count} items)")

    if sum(per_cat_counts.values()) != kept_total:
        print("FATAL: per-category counts do not sum to kept total",
              file=sys.stderr)
        return 3
    return 0


if __name__ == "__main__":
    sys.exit(main())
